---
squash: false
build_from:
  arm64: f0rc3/barcodebuddy:latest
  aarch64: f0rc3/barcodebuddy:latest
  amd64: f0rc3/barcodebuddy:latest
  armv7: f0rc3/barcodebuddy:latest
  i386: f0rc3/barcodebuddy:latest
args: {}
