name: Docker Publish x64 Release

on:
  workflow_dispatch:

env:
  IMAGE_NAME: barcodebuddy-docker
  DOCKER_FILE: Dockerfile
  VERSION: v1.6.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VERSION="${VERSION}" --file $DOCKER_FILE --tag f0rc3/barcodebuddy-docker:latest .

      - name: Push image
        run: docker push f0rc3/barcodebuddy-docker:latest
