name: Docker Publish x64

on:
  workflow_dispatch:

env:
  IMAGE_NAME: barcodebuddy-docker
  DOCKER_FILE: Dockerfile.dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build --push --file $DOCKER_FILE --tag f0rc3/barcodebuddy-docker:latest-dev .
