name: Docker Publish arm32 Release

on:
  workflow_dispatch:


env:
  DOCKER_FILE: Dockerfile.armhf
  ARCH: arm32v7
  VERSION: v1.6.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --file $DOCKER_FILE \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VERSION="${VERSION}" \
            --tag f0rc3/barcodebuddy-docker:arm32v7-latest \
            --platform linux/arm/v6 --push .
