name: Docker Publish i386

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number of new release'     
        required: true


env:
  DOCKER_FILE: Dockerfile.dev.i386
  ARCH: i386

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --file $DOCKER_FILE \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VERSION="${{ github.event.inputs.version }}" \
            --tag f0rc3/barcodebuddy-docker:i386-latest-dev \
            --platform linux/i386 --push .
