name: Docker Publish x64 Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number of new release'     
        required: true


env:
  DOCKER_FILE: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VERSION="${{ github.event.inputs.version }}" --file $DOCKER_FILE --tag f0rc3/barcodebuddy-docker:latest .

      - name: Push image
        run: docker push f0rc3/barcodebuddy-docker:latest && docker tag f0rc3/barcodebuddy-docker:latest f0rc3/barcodebuddy-docker:${{ github.event.inputs.version }} && docker push f0rc3/barcodebuddy-docker:${{ github.event.inputs.version }}
